#!/bin/bash

echo "Vou buscar dados do sistema , posso continuar ? [s/n]"
read resposta
test "$resposta" = "n" && exit
echo 
echo "Data e Horário:"
date
echo 
echo "Uso do disco:"
df
echo 
echo "Usuários conectados:"
w

